In [1]:
import warnings

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import ClusterCentroids
from imblearn.combine import SMOTEENN

In [4]:
import psycopg2 as pg
import pandas.io.sql as psql
import requests
import pymysql 
from sqlalchemy import create_engine
from config import user
from config import password


db_string = f"postgresql://postgres:{password}@datastroke.c326vl9oo2i8.us-east-1.rds.amazonaws.com:5432/stroke_db"

In [5]:
engine = create_engine(db_string)
stroke_df = pd.read_sql_query("SELECT * FROM stroke_clean",engine)

In [6]:
stroke_df.drop('ID', inplace=True, axis=1)
stroke_df.head()


Gender   Age  Hypertension  HeartDisease EverMarried           Work  \
0    Male  67.0             0             1         Yes        Private   
1    Male  80.0             0             1         Yes        Private   
2  Female  49.0             0             0         Yes        Private   
3  Female  79.0             1             0         Yes  Self-employed   
4    Male  81.0             0             0         Yes        Private   

  Residence  Glucose   BMI          Smoking  Stroke  
0     Urban   228.69  36.6  formerly smoked       0  
1     Rural   105.92  32.5     never smoked       0  
2     Urban   171.23  34.4           smokes       0  
3     Rural   174.12  24.0     never smoked       0  
4     Urban   186.21  29.0  formerly smoked       0

In [7]:
# Create our features
X = stroke_df.drop("Stroke", axis=1)
X = pd.get_dummies(X)

# Create our target
y = stroke_df["Stroke"]

In [8]:
X.describe()

Age  Hypertension  HeartDisease      Glucose         BMI  \
count  4908.000000   4908.000000   4908.000000  4908.000000  4908.00000   
mean     42.868989      0.091891      0.049511   105.297402    28.89456   
std      22.555878      0.288901      0.216954    44.425550     7.85432   
min       0.000000      0.000000      0.000000    55.120000    10.30000   
25%      25.000000      0.000000      0.000000    77.067500    23.50000   
50%      44.000000      0.000000      0.000000    91.680000    28.10000   
75%      60.000000      0.000000      0.000000   113.495000    33.10000   
max      82.000000      1.000000      1.000000   271.740000    97.60000   

       Gender_Female  Gender_Male  EverMarried_No  EverMarried_Yes  \
count    4908.000000  4908.000000     4908.000000      4908.000000   
mean        0.590261     0.409739        0.347188         0.652812   
std         0.491836     0.491836        0.476125         0.476125   
min         0.000000     0.000000        0.000000         0.000000   
25%         0.000000     0.000000        0.000000         0.000000   
50%         1.000000     0.000000        0.000000         1.000000   
75%         1.000000     1.000000        1.000000         1.000000   
max         1.000000     1.000000        1.000000         1.000000   

       Work_Govt_job  Work_Never_worked  Work_Private  Work_Self-employed  \
count    4908.000000        4908.000000   4908.000000         4908.000000   
mean        0.128362           0.004482      0.572535            0.157905   
std         0.334526           0.066808      0.494761            0.364689   
min         0.000000           0.000000      0.000000            0.000000   
25%         0.000000           0.000000      0.000000            0.000000   
50%         0.000000           0.000000      1.000000            0.000000   
75%         0.000000           0.000000      1.000000            0.000000   
max         1.000000           1.000000      1.000000            1.000000   

       Work_children  Residence_Rural  Residence_Urban  Smoking_Unknown  \
count    4908.000000      4908.000000      4908.000000      4908.000000   
mean        0.136716         0.492665         0.507335         0.302160   
std         0.343582         0.499997         0.499997         0.459241   
min         0.000000         0.000000         0.000000         0.000000   
25%         0.000000         0.000000         0.000000         0.000000   
50%         0.000000         0.000000         1.000000         0.000000   
75%         0.000000         1.000000         1.000000         1.000000   
max         1.000000         1.000000         1.000000         1.000000   

       Smoking_formerly smoked  Smoking_never smoked  Smoking_smokes  
count              4908.000000           4908.000000     4908.000000  
mean                  0.170334              0.377343        0.150163  
std                   0.375964              0.484771        0.357268  
min                   0.000000              0.000000        0.000000  
25%                   0.000000              0.000000        0.000000  
50%                   0.000000              0.000000        0.000000  
75%                   0.000000              1.000000        0.000000  
max                   1.000000              1.000000        1.000000

In [9]:
# Check the balance of our target values
y.value_counts()

1    4699
0     209
Name: Stroke, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Oversampling

### Naive Random Oversampling

In [11]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({1: 3524, 0: 3524})

In [12]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
Log_model = LogisticRegression(solver='lbfgs', random_state=1)
Log_model.fit(X_resampled, y_resampled)

/Users/mariapalacio/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [13]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = Log_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7595908346972177

In [14]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 42,  10],
       [339, 836]])

In [15]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.11      0.81      0.71      0.19      0.76      0.58        52
          1       0.99      0.71      0.81      0.83      0.76      0.57      1175

avg / total       0.95      0.72      0.80      0.80      0.76      0.57      1227



In [17]:
prediction_results = {"y_test": y_test,"y_pred": y_pred}
prediction_results = pd.DataFrame(prediction_results)
prediction_results

y_test  y_pred
1555       1       0
287        1       1
3645       1       1
293        1       0
3308       1       1
...      ...     ...
924        1       1
3728       1       0
3651       1       1
3391       1       1
4869       1       0

[1227 rows x 2 columns]

In [18]:
new_path = "Resources/prediction_results.csv"
prediction_results.to_csv(new_path, index=True)

In [19]:
prediction_results.to_sql(name='prediction_results', con=engine, if_exists='replace')

### SMOTE Oversampling

In [20]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1).fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({1: 3524, 0: 3524})

In [21]:
# Train the Logistic Regression model using the resampled data
Log_model = LogisticRegression(solver='lbfgs', random_state=1)
Log_model.fit(X_resampled, y_resampled)

/Users/mariapalacio/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [22]:
# Calculated the balanced accuracy score
y_pred = Log_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5331833060556465

In [23]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   5,   47],
       [  35, 1140]])

In [24]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.12      0.10      0.97      0.11      0.31      0.09        52
          1       0.96      0.97      0.10      0.97      0.31      0.10      1175

avg / total       0.93      0.93      0.13      0.93      0.31      0.10      1227



In [25]:
d_2 = {"y_test": y_test,"y_pred": y_pred}
df_2 = pd.DataFrame(d_2)
df_2

y_test  y_pred
1555       1       1
287        1       1
3645       1       1
293        1       1
3308       1       1
...      ...     ...
924        1       1
3728       1       1
3651       1       1
3391       1       1
4869       1       1

[1227 rows x 2 columns]

# Undersampling

In [26]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 157, 1: 157})

In [27]:
# Train the Logistic Regression model using the resampled data
Log_model = LogisticRegression(solver='lbfgs', random_state=1)
Log_model.fit(X_resampled, y_resampled)

/Users/mariapalacio/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [28]:
# Calculated the balanced accuracy score
y_pred = Log_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5068085106382979

In [29]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  52,    0],
       [1159,   16]])

In [30]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.04      1.00      0.01      0.08      0.12      0.01        52
          1       1.00      0.01      1.00      0.03      0.12      0.01      1175

avg / total       0.96      0.06      0.96      0.03      0.12      0.01      1227



In [31]:
d_3 = {"y_test": y_test,"y_pred": y_pred}
df_3 = pd.DataFrame(d_3)
df_3

y_test  y_pred
1555       1       0
287        1       1
3645       1       0
293        1       0
3308       1       1
...      ...     ...
924        1       1
3728       1       0
3651       1       0
3391       1       0
4869       1       0

[1227 rows x 2 columns]

# Combination (Over and Under) Sampling

In [32]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN
smoteen = SMOTEENN(random_state=1)
X_resampled, y_resampled = smoteen.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 4433, 1: 3570})

In [33]:
# Train the Logistic Regression model using the resampled data
Log_model = LogisticRegression(solver='lbfgs', random_state=1)
Log_model.fit(X_resampled, y_resampled)

/Users/mariapalacio/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [34]:
# Calculated the balanced accuracy score
y_pred = Log_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7096563011456629

In [35]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  28,   24],
       [ 140, 1035]])

In [36]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.17      0.54      0.88      0.25      0.69      0.46        52
          1       0.98      0.88      0.54      0.93      0.69      0.49      1175

avg / total       0.94      0.87      0.55      0.90      0.69      0.49      1227



In [37]:
d_4 = {"y_test": y_test,"y_pred": y_pred}
df_4 = pd.DataFrame(d_4)
df_4

y_test  y_pred
1555       1       1
287        1       1
3645       1       1
293        1       1
3308       1       1
...      ...     ...
924        1       1
3728       1       1
3651       1       1
3391       1       1
4869       1       0

[1227 rows x 2 columns]